# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "Whisper" ]
  pull_request:
    branches: [ "Whisper" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle User Files
      uses: actions/cache@v4
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
    - name: Cache Gradle Files
      uses: actions/cache@v4
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      env:
        ARCLIGHT_FILES_TOKEN: ${{ secrets.ARCLIGHT_FILES_TOKEN }}
      run: |
        ./gradlew cleanBuild build collect uploadFiles --no-daemon --stacktrace
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Arclight 
        path: ./build/libs/*.jar
